---
version: '2'


services:
  feed_watchdog:
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  fw_scheduler:
    volumes:
      - .:/app

  fw_processor:
    volumes:
      - .:/app

  redis:
    ports:
      - 6379:6379
