---
version: '2'


services:
  feed_watchdog:
    container_name: feed_watchdog
    build:
      context: .
      target: development
    env_file: server/.env
    hostname: feed_watchdog
    image: feed_watchdog:dev
    restart: "no"
    volumes:
      - ./public:/var/www/public

  fw_scheduler:
    command: python manage.py run_scheduler
    container_name: fw_scheduler
    env_file: server/.env
    hostname: fw_scheduler
    image: feed_watchdog:dev
    restart: "no"

  fw_processor:
    command: python -m processors
    container_name: fw_processor
    env_file: server/.env
    hostname: fw_processor
    image: feed_watchdog:dev
    restart: "no"

  redis:
    container_name: redis
    hostname: redis
    image: redis:7
    restart: "no"
