---
version: '2'


services:
  feed_watchdog:
    container_name: feed_watchdog
    build:
      context: .
      target: development
    env_file: server/.env
    hostname: feed_watchdog
    image: feed_watchdog:dev
    restart: "no"
    depends_on:
      - mongo

  fw_scheduler:
    command: python -m workers.scheduler
    container_name: fw_scheduler
    env_file: server/.env
    hostname: fw_scheduler
    image: feed_watchdog:dev
    depends_on:
      - redis
    restart: "no"

  fw_processor:
    command: python -m processors
    container_name: fw_processor
    env_file: server/.env
    hostname: fw_processor
    image: feed_watchdog:dev
    depends_on:
      - redis
    restart: "no"

  redis:
    container_name: redis
    hostname: redis
    image: redis:7
    restart: "no"

  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:6
    restart: "no"
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo: {}
