---
version: '2'


services:
  devtools:
    command: sleep infinity
    env_file: server/.env
    image: feed_watchdog:dev
    restart: "no"
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  feed_watchdog:
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  fw_scheduler:
    volumes:
      - .:/app

  fw_processor:
    volumes:
      - .:/app

  redis:
    ports:
      - 6379:6379
