---
version: '2'


services:
  feed_watchdog:
    image: yakim/feed_watchdog:latest
    build:
      target: production
    restart: unless-stopped

  fw_scheduler:
    image: yakim/feed_watchdog:latest
    restart: unless-stopped

  fw_processor:
    image: yakim/feed_watchdog:latest
    restart: unless-stopped
