---

x-feed-watchdog: &fw-common
  build:
    context: .
    target: development
  image: feed_watchdog:dev
  env_file: .env
  volumes:
    - .:/app

x-worker: &fw-worker-common
  <<: *fw-common
  depends_on:
    - feed_watchdog_api
    - redis
  restart: "on-failure"

services:
  feed_watchdog_api:
    <<: *fw-common
    container_name: feed_watchdog_api
    hostname: feed_watchdog_api
    restart: "no"
    depends_on:
      - mongo4
    ports:
      - "8000:8000"

  publish_streams_by_schedule_worker:
    <<: *fw-worker-common
    command: python -m feed_watchdog.workers.run_worker publish_streams_by_schedule

  fetch_posts_from_streams_worker:
    <<: *fw-worker-common
    command: python -m feed_watchdog.workers.run_worker fetch_posts_from_streams

  send_messages_worker:
    <<: *fw-worker-common
    command: python -m feed_watchdog.workers.run_worker send_messages

  mock_feed_server:
    image: feed_watchdog:dev
    container_name: mock_feed_server
    hostname: mock_feed_server
    command: python -m development.mock_feed_server
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8001:8001"

  redis:
    container_name: redis
    hostname: redis
    image: redis:7
    restart: "no"
    ports:
      - 6379:6379

  mongo4:
    container_name: mongo4
    hostname: mongo4
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    restart: "no"
    ports:
      - "27017:27017"
    volumes:
      - ./createUser.js:/docker-entrypoint-initdb.d/createUser.js
      - mongo4:/data/db

volumes:
  mongo4: {}
