# Generated by Django 4.0.4 on 2022-05-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receiver",
            name="recipient",
        ),
        migrations.AddField(
            model_name="receiver",
            name="options",
            field=models.JSONField(
                blank=True, default=dict, help_text="Receiver options"
            ),
        ),
    ]
