# Generated by Django 4.0.4 on 2022-07-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0007_filter_streamfilter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("cron", models.CharField(max_length=32, unique=True)),
                ("default", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="stream",
            name="intervals",
            field=models.ManyToManyField(blank=True, to="db.interval"),
        ),
    ]
