# Generated by Django 4.0.4 on 2022-07-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0008_interval_stream_intervals"),
    ]

    operations = [
        migrations.AddField(
            model_name="interval",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
