# Generated by Django 4.0.4 on 2022-07-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_stream_squash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='has_message_template',
        ),
        migrations.AddField(
            model_name='stream',
            name='receiver_options_override',
            field=models.JSONField(blank=True, default=dict, help_text='Receiver options'),
        ),
    ]
