# Generated by Django 4.0.4 on 2022-08-10 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0011_remove_stream_has_message_template_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("type", models.CharField(max_length=32)),
                (
                    "options",
                    models.JSONField(
                        blank=True, default=dict, help_text="Modifier options"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StreamModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.modifier",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.stream",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="streamfilter",
            name="filter",
        ),
        migrations.RemoveField(
            model_name="streamfilter",
            name="stream",
        ),
        migrations.DeleteModel(
            name="Filter",
        ),
        migrations.DeleteModel(
            name="StreamFilter",
        ),
    ]
