name: Production Deployment

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

jobs:
  deploy:
    name: Deploy To Production
    runs-on: ubuntu-latest
    steps:
      - name: install ssh keys
        # check this thread to understand why its needed:
        # https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} -p  > ~/.ssh/known_hosts
      - name: connect and update
        env:
          REF: ${{ github.event.inputs.git-ref }}
        run: |
          echo "SHA is: ${REF:-${GITHUB_SHA::7}}"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} \
            "cd projects/feed_watchdog && \
            FW_VERSION=${REF:-${GITHUB_SHA::7}} docker-compose up -d"
      - name: cleanup
        run: rm -rf ~/.ssh
